variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - init
  - repo
  - font
  - pkg-stable
  - pkg-skip
  - tex
  - ss
  - infra
  - llvm
  - util
  - misc
  - dl
  - edit
  - finish

init:
  stage: init
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-init$/
  except:
    - branches
  script:
    - until docker pull centos; do echo "Retry docker pull..."; done
    - gitlab-ci/build_stage.sh

.docker_build_stage_template: &docker_build_stage
  retry: 2
  tags:
    - docker
    - gpu
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

repo:
  stage: repo
  only:
    - /^(build|resume)-(init|repo)$/
  <<: *docker_build_stage

font:
  stage: font
  only:
    - /^(build|resume)-(init|repo|font)$/
  <<: *docker_build_stage

pkg-stable:
  stage: pkg-stable
  only:
    - /^(build|resume)-(init|repo|font|pkg-stable)$/
  <<: *docker_build_stage

pkg-skip:
  stage: pkg-skip
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip))$/
  <<: *docker_build_stage

tex:
  stage: tex
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|tex)$/
  <<: *docker_build_stage

ss:
  stage: ss
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|tex|ss)$/
  <<: *docker_build_stage

infra:
  stage: infra
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra)$/
  <<: *docker_build_stage

llvm:
  stage: llvm
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra|llvm)$/
  <<: *docker_build_stage

util:
  stage: util
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra|llvm|util)$/
  <<: *docker_build_stage

misc:
  stage: misc
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra|llvm|util|misc)$/
  <<: *docker_build_stage

dl:
  stage: dl
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra|llvm|util|misc|dl)$/
  <<: *docker_build_stage

edit:
  stage: edit
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra|llvm|util|misc|dl|edit)$/
  <<: *docker_build_stage

finish:
  stage: finish
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(stable|skip|all)|ss|tex|infra|llvm|util|misc|dl|edit|finish)$/
  except:
    - branches
  script:
    - docker login --password-stdin --username $CI_REGISTRY_USER $CI_REGISTRY <<< "$CI_REGISTRY_PASSWORD"
    - docker tag $CI_REGISTRY_IMAGE/centos:stage-edit $CI_REGISTRY_IMAGE/centos:latest
    - time docker push $CI_REGISTRY_IMAGE/centos:latest

