steps:
- bash: CI_JOB_STAGE="$SYSTEM_JOBDISPLAYNAME" gitlab-ci/build_stage.sh
- task: Docker@2
  inputs:
    containerRegistry: $(REGISTRY_SERVICE_CONNECTION)
    repository: $(CI_REGISTRY_IMAGE)/$(BASE_DISTRO)
    command: 'push'
    tags: stage-$(System.JobDisplayName)
